import { readDraft, writeDraft, readMedia, saveMedia, removeMedia, classifyMediaFile } from './card-workspace.mjs';

export const days=[
{day:1,code:'OC-001',title:'从不说谎的诈骗师',hook:'她说的每句话都是真的，却骗过了所有人。',focus:'身份反差',question:'你觉得她是怎么骗人的？'},
{day:2,code:'OC-002',title:'记忆医生',hook:'每救一个人，她就会忘记一个名字。',focus:'悲剧代价',question:'你愿意让她救你吗？'},
{day:3,code:'OC-003',title:'害怕人类的魅魔',hook:'她能让任何人爱上她，却害怕被人靠近。',focus:'反差萌',question:'给她取什么名字？'},
{day:4,code:'OC-004',title:'一小时人偶',hook:'她每天只能醒来一小时。',focus:'陪伴与养成',question:'醒来的第一件事做什么？'},
{day:5,code:'OC-005',title:'弑神修女',hook:'她信仰神明，也负责处决神明。',focus:'暗黑视觉',question:'第一次阶段复盘'},
{day:6,code:'OC-006',title:'仿生刺客',hook:'她会爱上每一个刺杀目标。',focus:'赛博恋爱',question:'任务和爱人选哪个？'},
{day:7,code:'OC-007',title:'噩梦兔妖',hook:'她吃掉主人的噩梦，也吃掉部分记忆。',focus:'非人软萌',question:'你愿意收养她吗？'},
{day:8,code:'OC-008',title:'死期花店老板',hook:'她能看见每位顾客的死亡日期。',focus:'都市幻想',question:'她应该告诉顾客吗？'},
{day:9,code:'OC-009',title:'通缉骑士',hook:'王国通缉她，罪名是保护了公主。',focus:'守护关系',question:'她真的背叛了吗？'},
{day:10,code:'OC-010',title:'失聪海妖',hook:'她的歌声让人陷入爱情，自己却听不见。',focus:'唯美情感',question:'汇总前十天数据'},
{day:11,code:'OC-011',title:'复制最高播放题材',hook:'保留获胜题材，替换身份与能力。',focus:'验证流量复制',question:'沿用最佳标题结构'},
{day:12,code:'OC-012',title:'复制最高评论题材',hook:'保留核心矛盾，创造全新角色。',focus:'验证讨论能力',question:'引导用户分析选择'},
{day:13,code:'OC-013',title:'复制最高收藏题材',hook:'保留画风与情绪，改变性别或年龄感。',focus:'验证收藏需求',question:'想看完整角色档案吗？'},
{day:14,code:'OC-014',title:'获胜元素组合',hook:'把最佳身份、代价与画风重新组合。',focus:'测试综合模型',question:'如果开放角色，你选哪位？'},
{day:15,code:'OC-015',title:'最终验证OC',hook:'用十四天数据制作最有潜力的新角色。',focus:'阶段代表作品',question:'发布总结与下一期预告'}];

export function calculateProgress(states){const total=states.length,completed=states.filter(Boolean).length;return{completed,total,percentage:total?Math.round(completed/total*100):0}}
export function filterDaysByPhase(items,phase){if(phase==='explore')return items.filter(({day})=>day<=10);if(phase==='optimize')return items.filter(({day})=>day>=11);return items}
export function createStorageKey(day){return`oc-action-plan-day-${day}`}
const readCompleted=day=>{try{return localStorage.getItem(createStorageKey(day))==='true'}catch{return false}};
const writeCompleted=(day,value)=>{try{localStorage.setItem(createStorageKey(day),String(value))}catch{}};
const objectUrls=new Map();
const promptTimers=new Map();

function clearObjectUrl(key){if(objectUrls.has(key)){URL.revokeObjectURL(objectUrls.get(key));objectUrls.delete(key)}}
function setObjectUrl(key,file){clearObjectUrl(key);const url=URL.createObjectURL(file);objectUrls.set(key,url);return url}

function cardTemplate(item){const checked=readCompleted(item.day),draft=readDraft(item.day),stage=item.day<=10?'探索期':'优化期';return`<article class="oc-workbench ${checked?'is-complete':''}" data-day="${item.day}">
<section class="media-studio"><div class="media-toolbar"><div class="media-tabs"><button class="${draft.activeMedia==='image'?'active':''}" data-media-tab="image">主图 <span data-asset-state="image">未上传</span></button><button class="${draft.activeMedia==='video'?'active':''}" data-media-tab="video">视频 <span data-asset-state="video">未上传</span></button></div><span class="stage-badge">${stage}</span></div><div class="media-canvas" data-media-canvas><div class="media-empty"><span class="media-empty-icon">＋</span><b>添加角色主图</b><p>图片最大15MB，视频最大200MB</p></div></div><div class="media-actions"><label class="upload-btn"><input type="file" accept="image/*" data-upload="image"><span>上传图片</span></label><label class="upload-btn secondary"><input type="file" accept="video/*" data-upload="video"><span>上传视频</span></label><button class="remove-media" data-remove-media hidden>删除当前素材</button></div></section>
<section class="workbench-content"><header class="workbench-head"><div><div class="workbench-index"><span>DAY ${String(item.day).padStart(2,'0')}</span><b>${item.code}</b></div><h2>${item.title}</h2><p>${item.hook}</p></div><label class="complete-switch"><input type="checkbox" ${checked?'checked':''} aria-label="标记第${item.day}天完成"><span>${checked?'已完成':'待制作'}</span></label></header><div class="brief-grid"><div><span>测试重点</span><b>${item.focus}</b></div><div><span>互动问题</span><b>${item.question}</b></div></div><div class="prompt-grid"><label class="prompt-field"><span><b>图片提示词</b><small>画面、角色、构图、光线</small></span><textarea data-draft-field="imagePrompt" placeholder="输入图片生成提示词…">${escapeText(draft.imagePrompt)}</textarea></label><label class="prompt-field"><span><b>视频提示词</b><small>动作、镜头、节奏、音效</small></span><textarea data-draft-field="videoPrompt" placeholder="输入视频生成提示词…">${escapeText(draft.videoPrompt)}</textarea></label></div><label class="notes-field"><span>制作备注</span><input data-draft-field="notes" value="${escapeAttribute(draft.notes)}" placeholder="例如：补一个眼神特写，结尾增加心跳音效"></label><footer class="workbench-footer"><span class="save-status">内容自动保存在当前浏览器</span><span class="asset-summary">图片未上传 · 视频未上传</span></footer></section></article>`}

function escapeText(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function escapeAttribute(value){return escapeText(value).replaceAll('"','&quot;')}

async function hydrateCard(card){const day=Number(card.dataset.day),draft=readDraft(day);let image=null,video=null;try{[image,video]=await Promise.all([readMedia(day,'image'),readMedia(day,'video')])}catch{};card.dataset.hasImage=String(Boolean(image));card.dataset.hasVideo=String(Boolean(video));card.querySelector('[data-asset-state="image"]').textContent=image?'已上传':'未上传';card.querySelector('[data-asset-state="video"]').textContent=video?'已上传':'未上传';let active=draft.activeMedia;if(active==='image'&&!image&&video)active='video';if(active==='video'&&!video&&image)active='image';card.querySelectorAll('[data-media-tab]').forEach(button=>button.classList.toggle('active',button.dataset.mediaTab===active));const asset=active==='image'?image:video;const canvas=card.querySelector('[data-media-canvas]');const remove=card.querySelector('[data-remove-media]');clearObjectUrl(`${day}:preview`);if(asset?.file){const url=setObjectUrl(`${day}:preview`,asset.file);canvas.innerHTML=active==='image'?`<img src="${url}" alt="${days[day-1]?.title||'OC角色'}主图">`:`<video src="${url}" controls muted preload="metadata"></video>`;remove.hidden=false}else{canvas.innerHTML=`<div class="media-empty"><span class="media-empty-icon">＋</span><b>${active==='image'?'添加角色主图':'添加预览视频'}</b><p>${active==='image'?'支持 JPG、PNG、WebP':'支持 MP4、WebM 等浏览器格式'}</p></div>`;remove.hidden=true}card.querySelector('.asset-summary').textContent=`图片${image?'已上传':'未上传'} · 视频${video?'已上传':'未上传'}`}

function attachCardEvents(card){const day=Number(card.dataset.day);card.querySelectorAll('[data-media-tab]').forEach(button=>button.addEventListener('click',()=>{const draft=readDraft(day);writeDraft(day,{...draft,activeMedia:button.dataset.mediaTab});hydrateCard(card)}));card.querySelectorAll('[data-upload]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const validation=classifyMediaFile(file);if(!validation.valid||validation.kind!==input.dataset.upload){showStatus(card,input.dataset.upload==='image'?'图片需小于15MB':'视频需小于200MB',true);input.value='';return}try{showStatus(card,'正在保存素材…');await saveMedia(day,input.dataset.upload,file);const draft=readDraft(day);writeDraft(day,{...draft,activeMedia:input.dataset.upload});await hydrateCard(card);showStatus(card,'素材已保存')}catch(error){showStatus(card,error.message||'素材保存失败',true)}input.value=''}));card.querySelector('[data-remove-media]').addEventListener('click',async()=>{const kind=readDraft(day).activeMedia;await removeMedia(day,kind);await hydrateCard(card);showStatus(card,'素材已删除')});card.querySelectorAll('[data-draft-field]').forEach(field=>field.addEventListener('input',()=>{clearTimeout(promptTimers.get(`${day}:${field.dataset.draftField}`));showStatus(card,'正在保存…');const timer=setTimeout(()=>{const current=readDraft(day);writeDraft(day,{...current,[field.dataset.draftField]:field.value});showStatus(card,'提示词已自动保存')},350);promptTimers.set(`${day}:${field.dataset.draftField}`,timer)}));const checkbox=card.querySelector('.complete-switch input');checkbox.addEventListener('change',()=>{writeCompleted(day,checkbox.checked);card.classList.toggle('is-complete',checkbox.checked);card.querySelector('.complete-switch span').textContent=checkbox.checked?'已完成':'待制作';updateProgress()})}
function showStatus(card,text,error=false){const status=card.querySelector('.save-status');status.textContent=text;status.classList.toggle('error',error)}

async function renderDays(phase='all'){const container=document.querySelector('#day-grid');if(!container)return;objectUrls.forEach(url=>URL.revokeObjectURL(url));objectUrls.clear();container.innerHTML=filterDaysByPhase(days,phase).map(cardTemplate).join('');const cards=[...container.querySelectorAll('.oc-workbench')];cards.forEach(attachCardEvents);await Promise.all(cards.map(hydrateCard))}
function updateProgress(){const result=calculateProgress(days.map(({day})=>readCompleted(day)));document.querySelector('#progress-value').textContent=`${result.percentage}%`;document.querySelector('#progress-count').textContent=`${result.completed} / ${result.total} DAYS`;document.querySelector('#progress-ring').style.setProperty('--progress',`${result.percentage*3.6}deg`)}
function init(){renderDays();updateProgress();document.querySelectorAll('[data-phase]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-phase]').forEach(item=>item.classList.remove('is-active'));button.classList.add('is-active');renderDays(button.dataset.phase)}))}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);
