import { buildLinePoints, calculateValueScore } from './dashboard.mjs';

const demoPosts=[
{code:'OC-001',title:'从不说谎的诈骗师',date:'07-27',views:3280,likes:246,collects:71,comments:35,followers:18,purchaseIntent:3},
{code:'OC-002',title:'记忆医生',date:'07-28',views:5120,likes:438,collects:126,comments:62,followers:31,purchaseIntent:7},
{code:'OC-003',title:'害怕人类的魅魔',date:'07-29',views:2160,likes:108,collects:23,comments:17,followers:8,purchaseIntent:1},
{code:'OC-004',title:'一小时人偶',date:'07-30',views:6840,likes:592,collects:184,comments:81,followers:45,purchaseIntent:9},
{code:'OC-005',title:'弑神修女',date:'07-31',views:4350,likes:317,collects:93,comments:40,followers:22,purchaseIntent:5}
];

export function aggregateStats(posts){const totals=posts.reduce((acc,p)=>{acc.views+=Number(p.views)||0;acc.interactions+=(Number(p.likes)||0)+(Number(p.collects)||0)+(Number(p.comments)||0);acc.followers+=Number(p.followers)||0;return acc},{views:0,interactions:0,followers:0});return{...totals,engagementRate:totals.views?Number((totals.interactions/totals.views*100).toFixed(2)):0}}
export function classifyPost(post){const views=Number(post.views)||0;const engagement=views?((Number(post.likes)||0)+(Number(post.collects)||0)+(Number(post.comments)||0))/views:0;if((Number(post.purchaseIntent)||0)>=3&&engagement>=.05)return'商品型';if(engagement>=.06||(Number(post.collects)||0)/Math.max(views,1)>=.015)return'潜力型';return'需调整'}
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n);

function renderLineChart(posts){
  const width=760,height=270,padL=55,padR=25,padT=24,padB=42;
  const values=posts.map(p=>p.views);const maxRaw=Math.max(...values,1);const max=Math.ceil(maxRaw/2000)*2000;
  const normalized=values.map(v=>v/max*100);const points=buildLinePoints(normalized,width-padL+padR,height-padT+padB,0).map(p=>({x:padL+p.x*(width-padL-padR)/(width-padL+padR),y:padT+p.y*(height-padT-padB)/(height-padT+padB)}));
  const line=points.map(p=>`${p.x},${p.y}`).join(' ');const area=`${points[0].x},${height-padB} ${line} ${points.at(-1).x},${height-padB}`;
  const avg=values.reduce((a,b)=>a+b,0)/values.length;const avgY=padT+(1-avg/max)*(height-padT-padB);
  const yTicks=[0,.25,.5,.75,1].map(r=>({value:Math.round(max*(1-r)),y:padT+r*(height-padT-padB)}));
  document.querySelector('#line-chart').innerHTML=`<svg class="line-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="单篇播放趋势图"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2563eb" stop-opacity=".22"/><stop offset="1" stop-color="#2563eb" stop-opacity=".02"/></linearGradient></defs>${yTicks.map(t=>`<line class="chart-grid" x1="${padL}" y1="${t.y}" x2="${width-padR}" y2="${t.y}"/><text class="chart-axis" x="${padL-10}" y="${t.y+3}" text-anchor="end">${t.value>=1000?(t.value/1000)+'k':t.value}</text>`).join('')}<line class="chart-average" x1="${padL}" y1="${avgY}" x2="${width-padR}" y2="${avgY}"/><text class="chart-axis" x="${width-padR}" y="${avgY-7}" text-anchor="end">平均 ${fmt(Math.round(avg))}</text><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${line}"/>${points.map((p,i)=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="5"/><text class="chart-label" x="${p.x}" y="${p.y-12}" text-anchor="middle">${fmt(values[i])}</text><text class="chart-axis" x="${p.x}" y="${height-15}" text-anchor="middle">${posts[i].code}</text>`).join('')}</svg>`;
}

function renderRank(posts){const ranked=[...posts].map(p=>({...p,score:calculateValueScore(p)})).sort((a,b)=>b.score-a.score);document.querySelector('#rank-list').innerHTML=ranked.map((p,i)=>`<div class="rank-item"><span class="rank-num">${i+1}</span><div class="rank-name"><b>${p.title}</b><span>${p.code}</span></div><div class="score-track"><i style="width:${p.score}%"></i></div><span class="rank-score">${p.score}</span></div>`).join('')}

function renderDashboard(posts){const totals=aggregateStats(posts);document.querySelector('#total-views').textContent=fmt(totals.views);document.querySelector('#total-interactions').textContent=fmt(totals.interactions);document.querySelector('#engagement-rate').textContent=`${totals.engagementRate}%`;document.querySelector('#new-followers').textContent=`+${fmt(totals.followers)}`;renderLineChart(posts);renderRank(posts);document.querySelector('#post-table-body').innerHTML=posts.map(p=>{const rate=p.views?((p.likes+p.collects+p.comments)/p.views*100).toFixed(2):'0.00';const type=classifyPost(p);const score=calculateValueScore(p);return`<tr><td><div class="post-cell"><b>${p.title}</b><span>${p.code}</span></div></td><td>${p.date}</td><td>${fmt(p.views)}</td><td>${fmt(p.likes)}</td><td>${fmt(p.collects)}</td><td>${fmt(p.comments)}</td><td>${rate}%</td><td>+${p.followers}</td><td>${p.purchaseIntent}</td><td><span class="score-badge">${score}</span></td><td><span class="signal signal-${type}">${type}</span></td></tr>`}).join('');const ranked=[...posts].sort((a,b)=>calculateValueScore(b)-calculateValueScore(a));const best=ranked[0];const second=ranked[1];document.querySelector('#decision-copy').innerHTML=`<p><b>${best.code}《${best.title}》综合价值最高。</b>它同时具备较高收藏、涨粉和购买意向。下一条建议保留它的情绪机制与开头节奏，替换角色身份；${second.code}可作为第二参考方向。</p>`}

function init(){renderDashboard(demoPosts);const key='oc-profile-v4';let saved=null;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{};const input=document.querySelector('#profile-url');if(saved?.url){input.value=saved.url;document.querySelector('#account-name').textContent='已绑定小红书账号';document.querySelector('#account-status').textContent=saved.url;document.querySelector('#sync-state').textContent='等待定时任务';document.querySelector('#sync-state').classList.add('online')}document.querySelector('#bind-focus')?.addEventListener('click',()=>input.focus());document.querySelector('#account-form')?.addEventListener('submit',e=>{e.preventDefault();const url=input.value.trim();if(!url.includes('xiaohongshu.com/user/profile/')){input.setCustomValidity('请输入有效的小红书个人主页链接');input.reportValidity();return}input.setCustomValidity('');localStorage.setItem(key,JSON.stringify({url,boundAt:new Date().toISOString()}));document.querySelector('#account-name').textContent='已绑定小红书账号';document.querySelector('#account-status').textContent=url;document.querySelector('#sync-state').textContent='等待定时任务';document.querySelector('#sync-state').classList.add('online')})}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);
